version: '3'
services:
  mysql:
    image: mysql:8.0
    networks:
      - cglee_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=test_db
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306

networks:
  cglee_network:
    driver: bridge